name: CI

on:
  push:
    branches: [ main, 'release/**', 'botapi/**' ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Значения по умолчанию — из GitHub Secrets
    env:
      TELEGRAM_TOKEN: ''
      TELEGRAM_CHAT_ID: ''

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Load secrets
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          TELEGRAM_SUPERGROUP_CHAT_ID: ${{ secrets.TELEGRAM_SUPERGROUP_CHAT_ID }}
          TELEGRAM_REPLY_TO_MESSAGE_ID: ${{ secrets.TELEGRAM_REPLY_TO_MESSAGE_ID }}
          TELEGRAM_EXISTING_PHOTO_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_PHOTO_FILE_ID }}
          TELEGRAM_EXISTING_DOCUMENT_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_DOCUMENT_FILE_ID }}
          TELEGRAM_EXISTING_AUDIO_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_AUDIO_FILE_ID }}
          TELEGRAM_EXISTING_VOICE_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_VOICE_FILE_ID }}
          TELEGRAM_EXISTING_VIDEO_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_VIDEO_FILE_ID }}
          TELEGRAM_EXISTING_VIDEO_NOTE_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_VIDEO_NOTE_FILE_ID }}
          TELEGRAM_EXISTING_STICKER_FILE_ID: ${{ secrets.TELEGRAM_EXISTING_STICKER_FILE_ID }}
        run: |
          if [ -n "$TELEGRAM_TOKEN_SECRET" ]; then
            echo "TELEGRAM_TOKEN=$TELEGRAM_TOKEN_SECRET" >> $GITHUB_ENV
          fi
          if [ -n "$TELEGRAM_CHAT_ID_SECRET" ]; then
            echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID_SECRET" >> $GITHUB_ENV
          fi

      # Загружаем .env и пишем его в GITHUB_ENV, чтобы работало в следующих шагах
      - name: Load .env file (if exists)
        run: |
          if [ -f .env ]; then
            echo "Loading .env…"
            while IFS= read -r line; do
              if [[ "$line" != \#* && "$line" == *=* ]]; then
                echo "$line" >> $GITHUB_ENV
              fi
            done < .env
          else
            echo ".env not found, using GitHub Secrets"
          fi

      # Кэш Go
      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Заменяем оригинальный модуль на форк
      - name: Use forked go-telegram-bot-api
        run: |
          go mod tidy

      # Узнаём архитектуру
      - name: Detect GOARCH
        id: goenv
        run: echo "arch=$(go env GOARCH)" >> "$GITHUB_OUTPUT"

      - name: Vet
        run: go vet ./...

      - name: Test (race)
        if: ${{ steps.goenv.outputs.arch != 'arm64' && steps.goenv.outputs.arch != 'arm' }}
        run: go test -v -count=1 -run '^Test_65_' ./...

      - name: Test (no race on ARM)
        if: ${{ steps.goenv.outputs.arch == 'arm64' || steps.goenv.outputs.arch == 'arm' }}
        run: go test -v -count=1 -run '^Test_65_' ./...

      # Telegram ping
      - name: Secrets self-check + Telegram ping (optional)
        if: always()
        run: |
          if [ -n "${TELEGRAM_TOKEN}" ]; then
            echo "::add-mask::${TELEGRAM_TOKEN}"
          fi

          echo "TELEGRAM_TOKEN set? $([ -n "${TELEGRAM_TOKEN}" ] && echo yes || echo no)"
          echo "TELEGRAM_CHAT_ID set? $([ -n "${TELEGRAM_CHAT_ID}" ] && echo yes || echo no)"

          if [ -n "${TELEGRAM_TOKEN}" ] && [ -n "${TELEGRAM_CHAT_ID}" ]; then
            MSG="✅ CI secrets OK on $(uname -s)/${{ steps.goenv.outputs.arch }} in $GITHUB_REPOSITORY ($GITHUB_REF_NAME)"
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" -d text="$MSG" > /dev/null || true
            echo "Telegram ping sent."
          else
            echo "Skip Telegram ping: secrets are missing."
          fi
