name: CI

on:
  push:
    branches: [ main, 'release/**', 'botapi/**' ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Load .env file (if exists)
        run: |
          if [ -f .env ]; then
            echo "Loading .env…"
            set -a
            source .env
            set +a
          else
            echo ".env not found, using GitHub Secrets"
          fi

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Detect GOARCH
        id: goenv
        run: echo "arch=$(go env GOARCH)" >> "$GITHUB_OUTPUT"

      - name: Vet
        run: go vet ./...

      - name: Test (race)
        if: ${{ steps.goenv.outputs.arch != 'arm64' && steps.goenv.outputs.arch != 'arm' }}
        run: go test ./... -race -count=1

      - name: Test (no race on ARM)
        if: ${{ steps.goenv.outputs.arch == 'arm64' || steps.goenv.outputs.arch == 'arm' }}
        run: go test ./... -count=1

      # === СЮДА ДОБАВЛЕН ТЕСТ СЕКРЕТОВ ===
      - name: Secrets self-check + Telegram ping (optional)
        if: always() # запускаем всегда, но сам шаг внутри пропустит без секретов
        run: |
          # Маскируем токен в логах (на случай загрузки из .env)
          if [ -n "${TELEGRAM_TOKEN}" ]; then
            echo "::add-mask::${TELEGRAM_TOKEN}"
          fi

          # Отладочная информация (без значений)
          echo "TELEGRAM_TOKEN set? $([ -n "${TELEGRAM_TOKEN}" ] && echo yes || echo no)"
          echo "TELEGRAM_CHAT_ID set? $([ -n "${TELEGRAM_CHAT_ID}" ] && echo yes || echo no)"

          # Если есть оба — отправим сообщение в Telegram
          if [ -n "${TELEGRAM_TOKEN}" ] && [ -n "${TELEGRAM_CHAT_ID}" ]; then
            MSG="✅ CI secrets OK on $(uname -s)/${{ steps.goenv.outputs.arch }} in $GITHUB_REPOSITORY ($GITHUB_REF_NAME)"
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
              -d chat_id="${TELEGRAM_CHAT_ID}" -d text="$MSG" > /dev/null || true
            echo "Telegram ping sent."
          else
            echo "Skip Telegram ping: secrets are missing."
          fi
